default['ushahidi']['dir'] = "/var/www"
default['ushahidi']['db']['schema'] = "ushahidi"
default['ushahidi']['db']['user'] = "ushahidi"
default['ushahidi']['db']['password'] = "eweshah1d1"
default['ushahidi']['application']['version'] = "master"
default['ushahidi']['application']['url'] = "localhost.localdomain"
default['ushahidi']['mail']['user'] = "cict.rti@gmail.com"
default['ushahidi']['mail']['password'] = "z7haoTHBoZp"
